com:
 neo:
  title: 纯洁的微笑
  description: 分享生活和技术
EhCache:
  caches:
    - name: userCache #缓存名称
      eternal: false #是否永不过期 默认false 如果为false那么还要根据timeToIdleSeconds，timeToLiveSeconds判断。
      max-elements-in-memory: 100 #cache 中最多可以存放的元素的数量 默认值100
      time-to-idle-seconds: 0 #对象空闲时间，指对象在多长时间没有被访问就会失效。只对eternal为false的有效。默认值0，表示一直可以访问。以秒为单位。
      time-to-live-seconds: 0 #对象存活时间，指对象从创建到失效所需要的时间。只对eternal为false的有效。默认值0，表示一直可以访问。以秒为单位。
      overflow-to-disk: true #如果内存中数据超过内存限制，是否要缓存到磁盘上。默认false
      disk-persistent: false #否在磁盘上持久化。指重启jvm后，数据是否有效。默认为false。
      max-elements-on-disk: 100 #在磁盘上缓存的element的最大数目，默认值为0，表示不限制。
      disk-spool-buffer-size-mB: 30 #DiskStore使用的磁盘大小，默认值30MB。每个cache使用各自的DiskStore。
      disk-expiry-thread-interval-seconds: 120 #对象检测线程运行时间间隔。标识对象状态的线程多长时间运行一次。以秒为单位。默认120 秒
    - name: roleCache #缓存名称
      eternal: false #是否永不过期 默认false 如果为false那么还要根据timeToIdleSeconds，timeToLiveSeconds判断。
      max-elements-in-memory: 100 #cache 中最多可以存放的元素的数量 默认值100
      time-to-idle-seconds: 0 #对象空闲时间，指对象在多长时间没有被访问就会失效。只对eternal为false的有效。默认值0，表示一直可以访问。以秒为单位。
      time-to-live-seconds: 0 #对象存活时间，指对象从创建到失效所需要的时间。只对eternal为false的有效。默认值0，表示一直可以访问。以秒为单位。
      overflow-to-disk: true #如果内存中数据超过内存限制，是否要缓存到磁盘上。默认false
      disk-persistent: false #否在磁盘上持久化。指重启jvm后，数据是否有效。默认为false。
      max-elements-on-disk: 100 #在磁盘上缓存的element的最大数目，默认值为0，表示不限制。
      disk-spool-buffer-size-mB: 30 #DiskStore使用的磁盘大小，默认值30MB。每个cache使用各自的DiskStore。
      disk-expiry-thread-interval-seconds: 120 #对象检测线程运行时间间隔。标识对象状态的线程多长时间运行一次。以秒为单位。默认120 秒  

# 使用druid连接池
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: admin
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,log4j
        logSlowSql: true
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # mybatis的mapper.xml文件的路径
  type-aliases-package: com.example.app.demo.pojo  # mybatis的model所在的包

